version: "3.8"

services:
  api:
    image: api_server
    build:
      context: ./VL-Api-Server/Source
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Settings__Database__Host=db
    ports:
      - 8080:80
    depends_on: 
      - db
  
  db:
    image: mongo:4.4
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=VisitorLog 
    volumes:
      - c:/DATA/VisitorLog:/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: --quiet --bind_ip_all --dbpath /mongodb --directoryperdb --replSet MyRepSet