version: "3.8"

services:
  api:
    image: ${Repository_Name}/api
    build:
      context: ${DockerFile_Location}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Settings__Database__Host=db
    ports:
      - 8080:80
    depends_on: 
      - db
    restart: always
  
  db:
    image: mongo:4.4
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${Database_Name} 
    volumes:
      - ${Data_Folder_On_Host}:/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: --quiet --bind_ip_all --dbpath /mongodb --directoryperdb --replSet ${ReplicaSet_Name}
    restart: always