version: "3.8"

### This is the base configuation.
### run `docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d` in production
### for development run `docker-compose up` 

services:
  api:
    image: visitorlog/api
    build:
      context: ./VL-Api-Server/Source
    environment:
      - Settings__Database__Host=db
      - Settings__Email__Username # these must be set in the production server shell. not needed for development.
      - Settings__Email__Password
      - Settings__Email__FromEmail
      - Settings__Auth__SigningKey    
    depends_on: 
      - db
    restart: always

  db:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=VisitorLog
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: --quiet --bind_ip_all --dbpath /mongodb --directoryperdb --replSet VLRepSet
    restart: always
    expose: 
      - 27017