### these values override (merge with) the base config when running `docker-compose up` during development

services:
  web:
    image: visitorlog/web:dev
    build:
      context: ../
      dockerfile: ./VL-Web-Client/Dockerfile
    ports: 
      - 8080:8080
    volumes: 
      - ../VL-Web-Client:/VisitorLog
    environment: 
      CHOKIDAR_USEPOLLING : "true" # only applies to windows. remove if developing in linux.
    depends_on: 
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  api:
    image: visitorlog/api:dev
    environment:
      ASPNETCORE_ENVIRONMENT : Development
    ports: 
      - 443:443
    restart: "no"
    
  db:
    command: --quiet --directoryperdb --replSet VLRepSet
    ports: 
      - 27017:27017
    restart: "no"