### these values override (merge with) the base config when running `docker-compose up` during development

services:
  web:
    image: visitorlog/web:dev
    build:
      context: ../VL-Web-Client
    ports: 
      - 8080:8080
    volumes: 
      - ../VL-Web-Client:/VisitorLog
    environment: 
      - CHOKIDAR_USEPOLLING=true # only applies to windows. remove if developing in linux.
    depends_on: 
      - api

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - 8888:80
    restart: "no"
    
  db:
    command: --quiet --bind_ip_all --directoryperdb --replSet VLRepSet
    ports: 
      - 27017:27017
    restart: "no"